### ISSUE TITLE
Not able to Understand The Metrics used

### ISSUE THREAD

**Issue by m-ali-awan** [mavillot/FUNSD-Entity-Linking#1]
Hi Mavillot, hope you are fine.

First of all, thanks for covering this complex topic. :)
I am struggling with the logic of metrics you have used like mRank etc. So, kindly if possible, share some resources so I can understand the logic behind these.

Thanks again.
Best Regards,

**Comment by mavillot** [comment]
Hi! I hope you are well. 

Thanks for your interest in my work.  You can find an explanation of the metrics here:
[Entity Linking](https://www.researchgate.net/publication/357046667_Text_Classification_Models_for_Form_Entity_Linking)
If you still have problems understanding it, don't hesitate to ask me!

Kind regards!

**Comment by m-ali-awan** [comment]
Thanks a lot, Mavillot, for the quick help :)

I will go through it.
Take care.
